mqtt:
  broker: "broker.mqtt"
  user: "user"
  password: "pass"
  topics:
    # Topic to listen on for connect/disconnect events
    events: "evcc/events"
    # Topic to send the target charging time. Use %s as placeholder for the vehicle id
    planSoc: "evcc/vehicles/%s/planSoc"
vehicles:
  - name: "ioniq6"
    soc: 80
    schedule:
      - day: "Monday"
        time: "07:00"
        soc: 70
      - day: "Wednesday"
        time: "07:00"
        # No soc specified; will use global soc (80)
      - day: "Friday"
        time: "07:00"
        soc: 90
      - day: "workday"
        time: "08:00"
        # Applies to all workdays not already specified
      - day: "weekend"
        time: "09:00"
        soc: 60
